/**
 * Per-file coexistence when upstream OpenSpec is already installed.
 * Preserves existing upstream openspec-* skills and opsx-* commands.
 */

import fs from 'node:fs';
import path from 'path';
import { FileSystemUtils } from '../utils/file-system.js';
import { detectLegacySlashCommands } from './legacy-cleanup.js';
import { qasCommandSubdir, qaspecSkillDirName } from './qaspec-commands.js';
import { RETIRED_QAS_WORKFLOW_IDS, RENAMED_QAS_WORKFLOW_IDS } from './profiles.js';
import { CommandAdapterRegistry } from './command-generation/index.js';

/** Upstream OpenSpec skill directory names (not generated by QASpec). */
export const UPSTREAM_OPENSPEC_SKILL_NAMES = [
  'openspec-explore',
  'openspec-new-change',
  'openspec-continue-change',
  'openspec-apply-change',
  'openspec-ff-change',
  'openspec-sync-specs',
  'openspec-archive-change',
  'openspec-bulk-archive-change',
  'openspec-verify-change',
  'openspec-onboard',
  'openspec-propose',
] as const;

/** Workflow IDs whose opsx-* commands belong to upstream OpenSpec. */
export const UPSTREAM_LEGACY_WORKFLOW_IDS = [
  'new',
  'continue',
  'apply',
  'ff',
  'sync',
  'bulk-archive',
  'verify',
  'onboard',
  'propose',
] as const;

const upstreamSkillDirs = new Set<string>(UPSTREAM_OPENSPEC_SKILL_NAMES);
const upstreamWorkflowIds = new Set<string>(UPSTREAM_LEGACY_WORKFLOW_IDS);

export function formatUpstreamCoexistenceSummary(preservedSkills: number, preservedCommands: number): string {
  if (preservedSkills === 0 && preservedCommands === 0) {
    return '';
  }
  const parts: string[] = [];
  if (preservedSkills > 0) {
    parts.push(`${preservedSkills} existing upstream openspec-* skill${preservedSkills === 1 ? '' : 's'}`);
  }
  if (preservedCommands > 0) {
    parts.push(`${preservedCommands} existing upstream opsx-* command${preservedCommands === 1 ? '' : 's'}`);
  }
  return `Upstream OpenSpec detected — preserved ${parts.join(' and ')}`;
}

export async function shouldSkipUpstreamSkillWrite(
  skillFilePath: string,
  dirName: string,
  upstreamActive: boolean
): Promise<boolean> {
  if (!upstreamActive || !upstreamSkillDirs.has(dirName)) {
    return false;
  }
  return FileSystemUtils.fileExists(skillFilePath);
}

export async function shouldSkipUpstreamCommandWrite(
  commandFilePath: string,
  commandId: string,
  upstreamActive: boolean
): Promise<boolean> {
  if (!upstreamActive || !upstreamWorkflowIds.has(commandId)) {
    return false;
  }
  return FileSystemUtils.fileExists(commandFilePath);
}

export function isUpstreamOpenspecSkillDir(dirName: string): boolean {
  return upstreamSkillDirs.has(dirName);
}

export function isUpstreamLegacyWorkflow(workflow: string): boolean {
  return upstreamWorkflowIds.has(workflow);
}

/**
 * Removes legacy QASpec-installed openspec-* skill directories when upstream is not active.
 */
export async function removeLegacyQaspecSkillDirs(
  skillsDir: string,
  upstreamOpenSpecActive: boolean
): Promise<number> {
  if (upstreamOpenSpecActive) {
    return 0;
  }

  let removed = 0;
  for (const dirName of UPSTREAM_OPENSPEC_SKILL_NAMES) {
    const skillDir = path.join(skillsDir, dirName);
    try {
      if (fs.existsSync(skillDir)) {
        await fs.promises.rm(skillDir, { recursive: true, force: true });
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }

  return removed;
}

/**
 * Removes legacy QASpec-installed slash command files when upstream is not active.
 */
export async function removeLegacyQaspecCommandFiles(
  projectPath: string,
  upstreamOpenSpecActive: boolean
): Promise<number> {
  if (upstreamOpenSpecActive) {
    return 0;
  }

  const slashResult = await detectLegacySlashCommands(projectPath);

  let removed = 0;
  for (const relativePath of slashResult.files) {
    const base = path.basename(relativePath);
    if (!base.startsWith('opsx-') && !base.startsWith('openspec-')) {
      continue;
    }
    const fullPath = path.join(projectPath, relativePath);
    try {
      if (fs.existsSync(fullPath)) {
        await fs.promises.unlink(fullPath);
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }

  return removed;
}

/**
 * Removes skill directories for retired QASpec workflow ids (e.g. qaspec-explore).
 */
export async function removeRetiredQaspecSkillDirs(skillsDir: string): Promise<number> {
  let removed = 0;
  for (const workflowId of RETIRED_QAS_WORKFLOW_IDS) {
    const skillDir = path.join(skillsDir, qaspecSkillDirName(workflowId));
    try {
      if (fs.existsSync(skillDir)) {
        await fs.promises.rm(skillDir, { recursive: true, force: true });
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }
  return removed;
}

/**
 * Removes skill directories for renamed legacy QASpec workflow ids (e.g. qaspec-matrix).
 */
export async function removeRenamedQaspecSkillDirs(skillsDir: string): Promise<number> {
  let removed = 0;
  for (const legacyId of Object.keys(RENAMED_QAS_WORKFLOW_IDS)) {
    const skillDir = path.join(skillsDir, qaspecSkillDirName(legacyId));
    try {
      if (fs.existsSync(skillDir)) {
        await fs.promises.rm(skillDir, { recursive: true, force: true });
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }
  return removed;
}

/**
 * Removes command files for renamed legacy QASpec workflow ids.
 */
export async function removeRenamedQaspecCommandFiles(
  projectPath: string,
  toolId: string
): Promise<number> {
  let removed = 0;
  const adapter = CommandAdapterRegistry.get(toolId);
  if (!adapter) return 0;

  for (const legacyId of Object.keys(RENAMED_QAS_WORKFLOW_IDS)) {
    const cmdPath = adapter.getFilePath(legacyId);
    const fullPath = path.isAbsolute(cmdPath) ? cmdPath : path.join(projectPath, cmdPath);
    try {
      if (fs.existsSync(fullPath)) {
        await fs.promises.unlink(fullPath);
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }
  return removed;
}

/**
 * Removes command files for retired QASpec workflow ids.
 */
export async function removeRetiredQaspecCommandFiles(
  projectPath: string,
  toolId: string
): Promise<number> {
  let removed = 0;
  const adapter = CommandAdapterRegistry.get(toolId);
  if (!adapter) return 0;

  for (const workflowId of RETIRED_QAS_WORKFLOW_IDS) {
    const cmdPath = adapter.getFilePath(workflowId);
    const fullPath = path.isAbsolute(cmdPath) ? cmdPath : path.join(projectPath, cmdPath);
    try {
      if (fs.existsSync(fullPath)) {
        await fs.promises.unlink(fullPath);
        removed++;
      }
    } catch {
      // Ignore errors
    }
  }
  return removed;
}

/**
 * Removes qsx/<workflow>.md commands that are not in the active profile.
 */
export async function removeDeselectedQasSubdirCommands(
  projectPath: string,
  desiredWorkflows: readonly string[]
): Promise<number> {
  const desired = new Set(desiredWorkflows);
  const subdir = qasCommandSubdir();
  const qasCommandDirs = [
    path.join(projectPath, '.cursor', 'commands', subdir),
    path.join(projectPath, '.claude', 'commands', subdir),
  ];

  let removed = 0;
  for (const qasCommandsDir of qasCommandDirs) {
    if (!fs.existsSync(qasCommandsDir)) {
      continue;
    }

    for (const entry of await fs.promises.readdir(qasCommandsDir)) {
      if (!entry.endsWith('.md')) continue;
      const workflowId = entry.slice(0, -3);
      if (desired.has(workflowId)) continue;
      try {
        await fs.promises.unlink(path.join(qasCommandsDir, entry));
        removed++;
      } catch {
        // Ignore errors
      }
    }
  }

  return removed;
}
